### PR TITLE
React 18, Upgrade Dependencies, Fix Copy/Paste

### PR DESCRIPTION
**Pull request by GeorgS**
Hi!

I've upgraded the dependencies and made sure it works with React 18. Also fixed some type errors I got during upgrading.

When trying the copy/paste the example I noticed that "[Object object]" was being pasted when copying cells. I tried to fix it, but I am not sure that the way I changed it is the way it was intended. Let me know if this should be handled differently. 

I have also bumped the version to `9.0.0`.

### CODE REVIEW

**Comment by rmdort** [comment]
Thank you. I have made my edits and merged your PR.

**Comment by GeorgS** [comment]
Thanks for the quick merge, appreciate it!
 I've noticed that the Readme states the port `6006` from my edit (due to the storybook upgrade) but should also be reverted to `9002` with the revert of storybook.

**Comment by rmdort** [comment]
Sure. I have updated readme. I had to downgrade Storybook to version 6, due to some incompatibility issues. Will upgrade once its stable.

**Comment by GeorgS** [comment]
When installing the package in the new 9+ version I cannot import, likely due to `"main": "dist/index.tsx",` - index.tsx does not existing in the dist folder.

**Comment by rmdort** [comment]
oops. Could you try with @rowsncolumns/grid@9.0.3

**Comment by GeorgS** [comment]
works now, thanks 👍

**Pull request merged**
